site_name: Focus Mode App
site_description: Linux/Wayland application blocker to boost productivity.
site_author: Gorlix
repo_url: https://github.com/Gorlix/focus-mode-app-linux
repo_name: focus-mode-app-linux

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Contributing: contributing.md
  - API Reference:
      - Core System: api/core.md
      - GUI / CLI: api/interfaces.md
